name: Build 

on: [ workflow_dispatch, push, pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [  macos-13, windows-latest, ubuntu-20.04 ] # ubuntu-latest, , macos-latest
        platform: [ x64 ] #x32, x64 ]
        exclude:
          - os: macos-latest
            platform: x32
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Put MSYS2_MinGW64 on PATH for windows
        if: matrix.os == 'windows-latest'
        # there is not yet an environment variable for this path from msys2/setup-msys2
        # We need this to get a gcc 11.2 that is new enough to compile the reference FMU3
        run: echo "C:\msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build
        run: cmake -G"Unix Makefiles" . && make

      - name: List windows dependencies
        if: matrix.os == 'windows-latest'
        shell: bash
        run: find . -name *.dll -exec echo {} \; -exec bash -c "objdump -p {} | grep 'DLL Name:'" \;

      - name: List linux dependencies
        if: matrix.os == 'ubuntu-20.04'
        shell: bash
        run: find . -name *.so -exec echo {} \; -exec ldd {} \;

      - name: List macos dependencies
        if: matrix.os == 'macos-13'
        shell: bash
        run: find . -name *.dylib -exec echo {} \; -exec otool -L {} \;


      - name: artifact upload windows
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: fmus-win
          path: |
            temp/**/*.dll
            temp/synchronous_control_cs.exe
            temp/synchronous_control_me.exe
          retention-days: 1

      - name: artifact upload windows
        if: matrix.os == 'macos-13'
        uses: actions/upload-artifact@v4
        with:
          name: fmus-mac
          path: |
            temp/**/*.dylib
          retention-days: 1




  final:
    runs-on: ubuntu-20.04
    needs: build

    strategy:
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          path: temp
          merge-multiple: true

      - name: Build
        run: find temp && cmake -G"Unix Makefiles" . && make

      - name: artifact upload 
        uses: actions/upload-artifact@v4
        with:
          name: fmus-final
          path: |
            fmus/*.fmu
            temp/synchronous_control*
          retention-days: 5


